### ISSUE TITLE
SSL Certificate Issues

### ISSUE THREAD

**Issue by dmtroyer** [matthewbentley/duplicity_b2#7]
The SSL Certificate verification is failing for me. Any thoughts? Maybe related to [this](http://stackoverflow.com/questions/27804710/python-urllib2-ssl-error/27826829#27826829)?

I have a super janky duplicity 0.7.06 install on freenas (python 2.7.9).

```
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 1532, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 1526, in with_tempdir
    fn()
  File "/usr/local/bin/duplicity", line 1364, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/duplicity/commandline.py", line 1116, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/lib/python2.7/site-packages/duplicity/commandline.py", line 1005, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/local/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/local/lib/python2.7/site-packages/duplicity/backends/b2backend.py", line 69, in __init__
    response = urllib2.urlopen(request)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

**Comment by dmtroyer** [comment]
OK, I figured it out. There are tons of hits for "Python 2.7.9 SSL: CERTIFICATE_VERIFY_FAILED". What worked for me on freenas (freebsd) was to create a symlink to the necessary certificate store ala:

`ln -s /usr/local/etc/ssl/cert.pem /etc/ssl/cert.pem`

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=189811

**Comment by dmtroyer** [comment]
That said, cheers on a wonderful tool @matthewbentley! I'm no longer beholden to the backblaze desktop apps, although they may have been a bit less costly altogether :sweat_smile:
